In [1]:
import numpy as np
arr = np.array([[12,34,45],[54,345,45]])
print(arr)
print(type(arr))

[[ 12  34  45]
 [ 54 345  45]]
<class 'numpy.ndarray'>


In [2]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [6]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
print(arr[0,4])

5


In [17]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[1, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12


In [15]:
print(arr.shape)  # Output: (2, 2, 3)


(2, 2, 3)


In [24]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 1nd dim: ', arr[1,-1])

Last element from 1nd dim:  10


In [30]:
r=np.array([23,45,43,45,32])
print(r)

[23 45 43 45 32]


In [31]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]
