In [10]:
import numpy as np
x =np.array(["car",'bike','train'])

#print(x)
fav = x[0]
for fav in x:
    print(fav)

car
bike
train


In [79]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr[1:4:2]) ; print(arr[::1])

[15 25]
[10 15 20 25 30 35 40]


In [54]:
arr = np.array([10, 15, 20, 25, 30, 35, 40],dtype = "i",ndmin=1)
print(arr,arr.ndim)

[10 15 20 25 30 35 40] 1


In [33]:
import numpy as np
arr = np.array([-1, 0, 1])
newarr = arr.astype(bool)
print(newarr)

[ True False  True]


In [73]:
print(arr[-2:0:-2])

[35 25 15]
